version: "3.7"

services:
  apache:
    restart: unless-stopped
    hostname: apache
    build: apache
    volumes:
      - ./data/wordpress:/var/www/html:rw
      - ./apache/sites-available:/etc/apache2/sites-available
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_ROOT_USER}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      
    ports:
      - 80:80
    depends_on:
      - php8
      - mysql

  php8:
    restart: unless-stopped
    hostname: php8
    build: php8
    volumes:
      - ./data/wordpress:/var/www/html:rw
    depends_on:
      - mysql
  
  mysql:
    hostname: mysql
    image: mysql:5.7
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped

  pma:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 881:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql

